# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_mod', models.CharField(blank=True, max_length=20)),
                ('product_name_mod', models.CharField(blank=True, max_length=2000)),
                ('product_url_mod', models.CharField(blank=True, max_length=20000)),
                ('product_price_mod', models.CharField(blank=True, max_length=20000)),
                ('category_name_mod', models.CharField(blank=True, max_length=20000)),
                ('overview_lst_mod', models.CharField(blank=True, max_length=20000)),
                ('main_picture_mod', models.CharField(blank=True, max_length=20000)),
                ('additional_images_mod', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
