# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 13:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinavAPI', '0003_auto_20161209_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodels',
            name='additional_images_mod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
