# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 14:20
from __future__ import unicode_literals

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinavAPI', '0004_auto_20161209_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodels',
            name='additional_images_mod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='productsmodels',
            name='overview_lst_mod',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
